Repository KILTprotocol/kilt-node, pull requests merged in 2021-11, with the labels that each got.

#289 fix: missing migrations for collective and membership pallets
  pallets/delegation/src/migrations.rs
  pallets/did/src/migrations.rs
  pallets/parachain-staking/src/migrations.rs
  runtimes/peregrine/src/lib.rs
  runtimes/spiritnet/src/lib.rs
  runtimes/standalone/src/lib.rs
Labels: 🐛 bug

#296 fix: tip
  primitives/src/fees.rs
  primitives/src/lib.rs
  runtimes/peregrine/src/lib.rs
  runtimes/spiritnet/src/lib.rs
Labels: 🐛 bug, ❤️ high

#293 feat: batch did
  .maintain/reset-spec/peregrine_dev_relay.py
  .maintain/reset-spec/peregrine_stg_relay.py
  .maintain/reset-spec/westend_relay.py
  pallets/did/src/did_details.rs
  pallets/did/src/lib.rs
  pallets/did/src/mock.rs
  runtimes/peregrine/src/lib.rs
  runtimes/peregrine/src/tests.rs
  runtimes/spiritnet/src/lib.rs
  runtimes/spiritnet/src/tests.rs
  runtimes/standalone/src/lib.rs
Labels: ✨ new feature

#295 feat: add deposit reclaim extrinsic for delegations
  pallets/delegation/Cargo.toml
  pallets/delegation/src/benchmarking.rs
  pallets/delegation/src/default_weights.rs
  pallets/delegation/src/lib.rs
  pallets/delegation/src/mock.rs
  pallets/delegation/src/tests.rs
  runtimes/peregrine/src/weights/delegation.rs
  runtimes/spiritnet/src/weights/delegation.rs
Labels: 💛 medium
