Repository KILTprotocol/kilt-node, pull requests merged in 2021-06, with the labels that each got.

#210 chore: upgrade to latest 0.9.5
  Cargo.lock
Labels: ❤️ high

#207 feat: new did creation logic
  pallets/did/Cargo.toml
  pallets/did/src/benchmarking.rs
  pallets/did/src/default_weights.rs
  pallets/did/src/did_details.rs
  pallets/did/src/errors.rs
  pallets/did/src/lib.rs
  pallets/did/src/mock.rs
  pallets/did/src/tests.rs
  runtimes/peregrine/src/weights/did.rs
Labels: Breaking JS Types, ✨ new feature

#202 fix: remove unused DispatchResultWithPostInfos
  pallets/attestation/src/lib.rs
  pallets/ctype/src/lib.rs
  pallets/delegation/src/lib.rs
  pallets/delegation/src/tests.rs
  pallets/did/src/lib.rs
  pallets/kilt-launch/src/lib.rs
Labels: 💚 low
