Repository KILTprotocol/kilt-node, pull requests merged in 2021-08, with the labels that each got.

#226 feat: delegation pallet storage refactor
  Cargo.lock
  pallets/attestation/src/default_weights.rs
  pallets/attestation/src/lib.rs
  pallets/attestation/src/tests.rs
  pallets/ctype/src/lib.rs
  pallets/delegation/Cargo.toml
  pallets/delegation/src/benchmarking.rs
  pallets/delegation/src/default_weights.rs
  pallets/delegation/src/delegation_hierarchy.rs
  pallets/delegation/src/deprecated.rs
  pallets/delegation/src/lib.rs
  pallets/delegation/src/migrations.rs
  pallets/delegation/src/migrations/v1.rs
  pallets/delegation/src/mock.rs
  pallets/delegation/src/tests.rs
  runtimes/peregrine/src/lib.rs
  runtimes/peregrine/src/weights/attestation.rs
  runtimes/peregrine/src/weights/delegation.rs
  runtimes/spiritnet/src/lib.rs
  runtimes/standalone/src/lib.rs
Labels: Breaking JS Types, 🐛 bug

#232 fix: allow any uid when resetting the chain spec
  .maintain/reset-spec/app.py
  .maintain/reset-spec/peregrine_kilt.py
  .maintain/reset-spec/peregrine_relay.py
  .maintain/reset-spec/peregrine_stg_kilt.py
  .maintain/reset-spec/peregrine_stg_relay.py
  dev-specs/kilt-parachain/peregrine-stg-kilt.json
Labels: 🐛 bug

#228 refactor: migrate runtime storage Vec, BTreeSet, BTreeMap to their bounded versions
  pallets/attestation/src/default_weights.rs
  pallets/attestation/src/lib.rs
  pallets/attestation/src/mock.rs
  pallets/delegation/src/benchmarking.rs
  pallets/delegation/src/default_weights.rs
  pallets/delegation/src/delegation_hierarchy.rs
  pallets/delegation/src/lib.rs
  pallets/delegation/src/migrations/v1.rs
  pallets/delegation/src/mock.rs
  pallets/did/src/benchmarking.rs
  pallets/did/src/default_weights.rs
  pallets/did/src/deprecated.rs
  pallets/did/src/did_details.rs
  pallets/did/src/errors.rs
  pallets/did/src/lib.rs
  pallets/did/src/migrations/v1.rs
  pallets/did/src/mock.rs
  pallets/did/src/mock_utils.rs
  pallets/did/src/tests.rs
  pallets/did/src/url.rs
  pallets/did/src/utils.rs
  pallets/kilt-launch/src/benchmarking.rs
  pallets/kilt-launch/src/default_weights.rs
  pallets/kilt-launch/src/lib.rs
  pallets/kilt-launch/src/mock.rs
  pallets/kilt-launch/src/tests.rs
  pallets/parachain-staking/src/benchmarking.rs
  pallets/parachain-staking/src/default_weights.rs
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
  pallets/parachain-staking/src/migrations/v2.rs
  pallets/parachain-staking/src/migrations/v3.rs
  pallets/parachain-staking/src/migrations/v4.rs
  pallets/parachain-staking/src/mock.rs
  pallets/parachain-staking/src/set.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
  runtimes/peregrine/src/lib.rs
  runtimes/peregrine/src/weights/attestation.rs
  runtimes/peregrine/src/weights/delegation.rs
  runtimes/peregrine/src/weights/did.rs
  runtimes/peregrine/src/weights/kilt_launch.rs
  runtimes/peregrine/src/weights/parachain_staking.rs
  runtimes/spiritnet/src/lib.rs
  runtimes/spiritnet/src/weights/kilt_launch.rs
  runtimes/spiritnet/src/weights/parachain_staking.rs
  runtimes/standalone/src/lib.rs
Labels: Breaking JS Types
