Repository KILTprotocol/kilt-node, pull requests merged in 2021-10, with the labels that each got.

#257 fix: mitigate DID pallet replay vulnerabilities
  .github/PULL_REQUEST_TEMPLATE.md
  pallets/attestation/src/mock.rs
  pallets/ctype/src/mock.rs
  pallets/delegation/src/mock.rs
  pallets/did/src/benchmarking.rs
  pallets/did/src/default_weights.rs
  pallets/did/src/did_details.rs
  pallets/did/src/errors.rs
  pallets/did/src/lib.rs
  pallets/did/src/migrations.rs
  pallets/did/src/mock.rs
  pallets/did/src/tests.rs
  primitives/src/constants.rs
  runtimes/peregrine/src/lib.rs
  runtimes/peregrine/src/weights/did.rs
  runtimes/spiritnet/src/lib.rs
  runtimes/standalone/src/lib.rs
Labels: ❤️ high, Breaking JS Types

#258 feat: add delegation storage deposits
  Cargo.lock
  pallets/attestation/Cargo.toml
  pallets/attestation/src/benchmarking.rs
  pallets/attestation/src/lib.rs
  pallets/attestation/src/mock.rs
  pallets/delegation/Cargo.toml
  pallets/delegation/src/benchmarking.rs
  pallets/delegation/src/default_weights.rs
  pallets/delegation/src/delegation_hierarchy.rs
  pallets/delegation/src/deprecated.rs
  pallets/delegation/src/lib.rs
  pallets/delegation/src/migrations.rs
  pallets/delegation/src/migrations/v1.rs
  pallets/delegation/src/mock.rs
  pallets/delegation/src/tests.rs
  primitives/src/constants.rs
  runtimes/peregrine/src/lib.rs
  runtimes/peregrine/src/weights/delegation.rs
  runtimes/standalone/src/lib.rs
Labels: 💛 medium, Breaking JS Types

#260 feat: remove service endpoints from DID details
  Cargo.lock
  pallets/delegation/Cargo.toml
  pallets/delegation/src/migrations.rs
  pallets/did/Cargo.toml
  pallets/did/src/benchmarking.rs
  pallets/did/src/default_weights.rs
  pallets/did/src/deprecated.rs
  pallets/did/src/deprecated/v1.rs
  pallets/did/src/deprecated/v2.rs
  pallets/did/src/did_details.rs
  pallets/did/src/errors.rs
  pallets/did/src/lib.rs
  pallets/did/src/migrations.rs
  pallets/did/src/migrations/v1.rs
  pallets/did/src/migrations/v2.rs
  pallets/did/src/mock.rs
  pallets/did/src/mock_utils.rs
  pallets/did/src/origin.rs
  pallets/did/src/tests.rs
  pallets/did/src/url.rs
  pallets/did/src/utils.rs
  pallets/kilt-launch/src/lib.rs
  pallets/parachain-staking/Cargo.toml
  primitives/Cargo.toml
  primitives/src/lib.rs
  runtimes/peregrine/src/lib.rs
  runtimes/peregrine/src/weights/did.rs
  runtimes/standalone/src/lib.rs
  support/Cargo.toml
  support/src/traits.rs
Labels: 💛 medium, Breaking JS Types

#266 fix: unwanted delegator state removal when tx fails
  pallets/parachain-staking/src/lib.rs
  pallets/parachain-staking/src/migrations.rs
  pallets/parachain-staking/src/migrations/v6.rs
  pallets/parachain-staking/src/tests.rs
  pallets/parachain-staking/src/types.rs
Labels: 🐛 bug
